name: goltens_mobile
description: Goltens (Android, iOS) (User/SubAdmin, Admin)
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  goltens_core:
    path: ../goltens_core

  cupertino_icons: ^1.0.2
  lottie: ^2.3.2
  dio: 4.0.2
  collection: ^1.17.1
  provider: ^6.0.5
  email_validator: ^2.0.1
  internet_connection_checker: ^1.0.0+1
  flutter_pdfview: 1.2.9
  photo_view: ^0.14.0
  video_player: ^2.6.1
  audioplayers: 3.0.1
  path_provider: ^2.0.14
  file_picker: ^5.2.11
  open_filex: ^4.3.2
  permission_handler: ^10.2.0
  intl_phone_field: ^3.1.0
  flutter_native_splash: ^2.2.19
  flutter_downloader: ^1.10.3
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1
  dropdown_textfield: ^1.0.8
  flutter_email_sender: ^5.1.0
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
